### ISSUE TITLE
Remove resources-vue

### ISSUE THREAD

**Issue by dhornbein** [dhornbein/denverfreelancing.com#13]
The folder `resources-vue` doesn't appear to be used, is there any reason to keep it in the code base @tomwhartung ?

**Comment by tomwhartung** [comment]
I was thinking the exact same thing.  I was going to try to delete it earlier to ensure it wasn't being used, but I do not yet have a development environment set up locally.  Being new to jekyll, I will probably need to install ruby and the whole bit, so will find time for getting in to all that in a day or so.

**Comment by dhornbein** [comment]
You can remove it without running jekyll.

**Comment by tomwhartung** [comment]
Yes but can I ensure the site still works without running jekyll?

**Comment by tomwhartung** [comment]
I could delete it, do a PR, and let someone else test it, if you like.

But I generally like to test my own changes.

**Comment by dhornbein** [comment]
Jekyll is fairly easy to install in my experience: https://jekyllrb.com/

You can talk to me on slack if you run into any issues.
